#!/bin/bash
. ../bin/setup_Pop-up-PKI
. ../bin/PopUpPKI-params
USERNAME_1=CA-2A
USEREMAIL_1=CA-2A@test.b70.net
DN_1="-subj /C=US/ST=California/L=Berkeley/DC=COM/DC=EXAMPLE/O=LCBO/OU=Test/CN=${USERNAME_1}"

sed -e "s/TEMPLATE_CA/${CA_NAME}/g" <${ETC}/Pop-up-PKI/template-sub-ca.cnf >tmp-1.cnf
sed -e "s/T_EMAIL/${USEREMAIL_1}/" <tmp-1.cnf >tmp-2.cnf

cat template-openssl.cnf tmp-2.cnf >${CA_DIR}/openssl.cnf
DUT_DN=${DN_1} SSLEAY_CONFIG=${SSLEAY_CONFIG} CA_DIR=${CA_DIR} CA_DAYS=${CA_DAYS} CERT_DAYS=${CERT_DAYS} \
  ${BIN}/CA.pl -newreq-nodes-param
DUT_DN=${DN_1} SSLEAY_CONFIG=${SSLEAY_CONFIG} CA_DIR=${CA_DIR} CA_DAYS=${CA_DAYS} CERT_DAYS=${CERT_DAYS} \
  ${BIN}/CA.pl -sign
cp newcert.pem ${PKI_OUT}/${USEREMAIL_1}_cert.pem
cp newreq.pem ${PKI_OUT}/${USEREMAIL_1}_req.pem
cp newkey.pem ${PKI_OUT}/${USEREMAIL_1}_key.pem

USERNAME_2=CA-2B
USEREMAIL_2=CA-2B@test.b70.net
DN_2="-subj /C=US/ST=California/L=Berkeley/DC=COM/DC=EXAMPLE/O=LCBO/OU=Test/CN=${USERNAME_2}"

sed -e "s/TEMPLATE_CA/${CA_NAME}/g" <${ETC}/Pop-up-PKI/template-sub-ca.cnf >tmp-1.cnf
sed -e "s/T_EMAIL/${USEREMAIL_2}/" <tmp-1.cnf >tmp-2.cnf

cat template-openssl.cnf tmp-2.cnf >${CA_DIR}/openssl.cnf
DUT_DN=${DN_2} SSLEAY_CONFIG=${SSLEAY_CONFIG} CA_DIR=${CA_DIR} CA_DAYS=${CA_DAYS} CERT_DAYS=${CERT_DAYS} \
  ${BIN}/CA.pl -newreq-nodes-param
DUT_DN=${DN_2} SSLEAY_CONFIG=${SSLEAY_CONFIG} CA_DIR=${CA_DIR} CA_DAYS=${CA_DAYS} CERT_DAYS=${CERT_DAYS} \
  ${BIN}/CA.pl -sign
cp newcert.pem ${PKI_OUT}/${USEREMAIL_2}_cert.pem
cp newreq.pem ${PKI_OUT}/${USEREMAIL_2}_req.pem
cp newkey.pem ${PKI_OUT}/${USEREMAIL_2}_key.pem

