#!/bin/bash
TROOT=opt/tester
TBIN=/${TROOT}/bin
echo initializing CA -$1-
echo $1 >this-ca.param
CA=`cat ./this-ca.param`

echo checking for files...
ls -l 1-create-CA 2-create-cert 3-sign-cert 9-clean
ls -l ${CA}-TEMPLATE.cnf ${CA}-sign.json ${CA}-member-TEMPLATE.json ${CA}.json

echo configuring CA -${CA}-
${TBIN}/configure-CA ${CA}.json

